services:
  postgres:
    image: postgres
    restart: always
    container_name: database-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
